# Generated by Django 4.2.3 on 2023-09-12 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macroeconomics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='economic_index',
            name='not_disabled',
            field=models.BooleanField(default=True),
        ),
    ]
