# Generated by Django 4.2.3 on 2023-09-23 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('macroeconomics', '0002_economic_index_not_disabled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='economic_index',
            name='path',
        ),
        migrations.AlterField(
            model_name='economic_index',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, null=True)),
                ('macro_economic_index', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='macroeconomics.economic_index')),
            ],
        ),
    ]
