# Generated by Django 4.2.3 on 2023-09-30 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macroeconomics', '0003_remove_economic_index_path_alter_economic_index_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='economic_index',
            name='slug',
            field=models.CharField(max_length=127, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='slug',
            field=models.CharField(max_length=127, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(max_length=127, verbose_name='Название разделала'),
        ),
    ]
