# Generated by Django 4.2.3 on 2024-01-05 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('macroeconomics', '0004_economic_index_slug_topic_slug_alter_topic_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='economic_index',
            name='not_disabled',
        ),
    ]
