# Generated by Django 4.2.3 on 2024-01-05 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('macroeconomics', '0005_remove_economic_index_not_disabled'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Economic_index',
            new_name='EconomicIndex',
        ),
    ]
