# Generated by Django 4.2.3 on 2024-01-05 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macroeconomics', '0006_rename_economic_index_economicindex'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='path',
        ),
        migrations.AddField(
            model_name='table',
            name='excel',
            field=models.FileField(blank=True, default=None, null=True, upload_to='excels'),
        ),
    ]
