# Generated by Django 4.2.3 on 2024-01-08 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macroeconomics', '0007_remove_table_path_table_excel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('doc', models.FileField(blank=True, default=None, null=True, upload_to='docs')),
            ],
        ),
    ]
